const promise = Promise.reject('Error');

promise.catch(console.log);